local _, p1xelUI = ...
local m = p1xelUI:CreateModule("Fonts")

local eventHandler = CreateFrame("Frame", nil, UIParent)
eventHandler:SetScript("OnEvent", function(self, event, ...)
    return self[event](self, ...)
end)

function m:OnLoad()
    -- Fonts.xml
    self:ShadowFont(GameFontNormal, 12)
    self:ShadowFont(GameFontNormalSmall, 10)
    self:ShadowFont(GameFontNormalLarge, 14)
    self:ShadowFont(NumberFontNormalSmall, 10)
    self:ShadowFont(GameNormalNumberFont, 12)
    self:ShadowFont(TextStatusBarText, 10)
    self:ShadowFont(GameFontHighlight, 12)
    self:ShadowFont(GameFontHighlightSmall, 10)
    self:ShadowFont(GameTooltipText, 12)
    self:ShadowFont(GameTooltipHeaderText, 14)
    self:ShadowFont(GameTooltipTextSmall, 10)
    self:ShadowFont(SystemFont_NamePlate, 9)
    self:ShadowFont(SystemFont_NamePlateLevel, 10)
    self:ShadowFont(SystemFont_NamePlateCastBar, 10)
    self:ShadowFont(SystemFont_NamePlateFixed, 14)
    self:ShadowFont(SystemFont_LargeNamePlateFixed, 20)
    self:ShadowFont(SystemFont_LargeNamePlate, 12)
    self:ShadowFont(SystemFont_Shadow_Huge3, 25)
    self:ShadowFont(SystemFont_Med2, 13)
    self:ShadowFont(SystemFont_Med3, 12)
    self:ShadowFont(SystemFont_Outline_Small, 10)
    self:ShadowFont(SystemFont_Outline, 13)
    self:ShadowFont(SystemFont_InverseShadow_Small, 10)
    self:ShadowFont(SystemFont_Huge1, 20)
    self:ShadowFont(SystemFont_Huge1_Outline, 20)
    self:ShadowFont(SystemFont_OutlineThick_Huge4, 26)
    self:ShadowFont(SystemFont_OutlineThick_WTF, 26)
    self:ShadowFont(SystemFont_Shadow_Small, 10)
    self:ShadowFont(SubSpellFont, 9, 1, 1, 1)
    self:ShadowFont(GameFontHighlightSmall2, 9)
    self:ShadowFont(GameFontNormalMed2, 14)
    self:ShadowFont(SystemFont_Shadow_Med3, 14)
    -- self:ShadowFont(PriceFont,14)
    self:ShadowFont(NumberFont_GameNormal, 10)
    self:ShadowFont(NumberFont_GameNormal, 10)
    self:ShadowFont(NumberFont_OutlineThick_Mono_Small, 12)
    self:ShadowFont(Number12Font_o1, 12)
    self:ShadowFont(NumberFont_Small, 12)
    -- self:ShadowFont(Number11Font, 11)
    -- self:ShadowFont(Number12Font, 12)
    -- self:ShadowFont(Number13Font, 13)
    -- self:ShadowFont(Number15Font,15)
    -- self:ShadowFont(Number16Font,16)
    -- self:ShadowFont(Number18Font,18)
    self:ShadowFont(NumberFont_Normal_Med,14)
    self:ShadowFont(NumberFont_Outline_Med,14)
    self:ShadowFont(NumberFont_Outline_Large,16)
    self:ShadowFont(NumberFont_Outline_Huge,30)
    self:ShadowFont(Fancy22Font,22)
    self:ShadowFont(QuestFont_Outline_Huge,18)
    self:ShadowFont(QuestFont_Enormous, 30)
    self:ShadowFont(QuestFont_Super_Huge,24)
    self:ShadowFont(QuestFont_Super_Huge_Outline,24)
    self:ShadowFont(QuestFont_Shadow_Small, 14)
    self:ShadowFont(SplashHeaderFont,24)
    -- self:ShadowFont(Game11Font_Shadow, 11)
    self:ShadowFont(Game11Font, 11)
    self:ShadowFont(Game12Font, 12)
    self:ShadowFont(Game13Font, 13)
    self:ShadowFont(Game13FontShadow, 13)
    self:ShadowFont(Game15Font, 15)
    self:ShadowFont(Game16Font, 16)
    self:ShadowFont(Game18Font, 18)
    self:ShadowFont(Game20Font, 20)
    self:ShadowFont(Game24Font, 24)
    self:ShadowFont(Game27Font, 27)
    self:ShadowFont(Game32Font, 32)
    self:ShadowFont(Game36Font, 36)
    -- self:ShadowFont(Game40Font, 40)
    self:ShadowFont(Game42Font, 42)
    self:ShadowFont(Game48Font, 48)
    self:ShadowFont(Game48FontShadow, 48)
    self:ShadowFont(Game60Font, 60)
    self:ShadowFont(Game120Font, 120)
    self:ShadowFont(Game11Font_o1, 11)
    self:ShadowFont(Game12Font_o1, 12)
    self:ShadowFont(Game13Font_o1, 13)
    self:ShadowFont(Game15Font_o1, 15)
    self:ShadowFont(DestinyFontMed, 14)
    self:ShadowFont(DestinyFontLarge, 18)
    self:ShadowFont(DestinyFontHuge, 32)
    self:ShadowFont(CoreAbilityFont, 30)
    self:ShadowFont(MailFont_Large, 15)
    self:ShadowFont(SpellFont_Small, 10)
    self:ShadowFont(InvoiceFont_Med, 12)
    self:ShadowFont(InvoiceFont_Small, 10)
    self:ShadowFont(AchievementFont_Small, 10)
    self:ShadowFont(ReputationDetailFont, 10)
    self:ShadowFont(FriendsFont_Normal, 12)
    -- self:ShadowFont(FriendsFont_11, 11)
    self:ShadowFont(FriendsFont_Small, 10)
    self:ShadowFont(FriendsFont_Large, 14)
    self:ShadowFont(FriendsFont_UserText, 11)
    self:ShadowFont(GameFont_Gigantic, 32)
    self:ShadowFont(ChatBubbleFont, 13)
    self:ShadowFont(ChatFontNormal, 13)
    self:ShadowFont(Fancy12Font, 12)
    self:ShadowFont(Fancy14Font, 14)
    self:ShadowFont(Fancy16Font, 16)
    self:ShadowFont(Fancy18Font, 18)
    self:ShadowFont(Fancy20Font, 20)
    self:ShadowFont(Fancy24Font, 24)
    self:ShadowFont(Fancy27Font, 27)
    self:ShadowFont(Fancy30Font, 30)
    self:ShadowFont(Fancy32Font, 32)
    self:ShadowFont(Fancy48Font, 48)
end

function m:ShadowFont(font, size, r, g, b, alpha)
    font:SetFont("Fonts\\FRIZQT__.TTF", size, "THINOUTLINE")
    font:SetShadowOffset(1, -1)

    if b ~= nil then
      font:SetTextColor(r, g, b, alpha)
    end
end

